services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: geneinsight-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: geneinsight
      MYSQL_USER: geneinsight_user
      MYSQL_PASSWORD: geneinsight_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - geneinsight-network

  # Spring Boot Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geneinsight-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/geneinsight
      SPRING_DATASOURCE_USERNAME: geneinsight_user
      SPRING_DATASOURCE_PASSWORD: geneinsight_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      ML_SERVICE_URL: https://least-won-grocery-children.trycloudflare.com
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      ml-service:
        condition: service_started
    networks:
      - geneinsight-network

  # Python ML Service
  ml-service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    container_name: geneinsight-ml
    ports:
      - "5000:5000"
    volumes:
      - ml_models:/app/models
    networks:
      - geneinsight-network

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: geneinsight-frontend
    environment:
      NEXT_PUBLIC_API_URL: https://georgia-detected-pupils-employ.trycloudflare.com
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - geneinsight-network

volumes:
  mysql_data:
  ml_models:

networks:
  geneinsight-network:
    driver: bridge
