app = "geneinsight-platform"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile.railway"

[env]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  TRANSFORMERS_CACHE = "/data/transformers_cache"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "10s"

[mounts]
  source = "model_cache"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[processes]
  app = "/app/start.sh"
