databases:
  - name: geneinsight-database
    databaseName: geneinsight
    user: geneinsight_user

services:
  # ML Service
  - type: web
    name: geneinsight-ml
    env: docker
    dockerfilePath: ./ml_service/Dockerfile
    dockerContext: ./ml_service
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health

  # Backend Service
  - type: web
    name: geneinsight-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: geneinsight-database
          property: connectionString
      - key: ML_SERVICE_URL
        fromService:
          type: web
          name: geneinsight-ml
          property: hostWithProtocol
      - key: MAIL_USERNAME
        value: noreply@geneinsight.com
      - key: MAIL_PASSWORD
        value: changeme
      - key: JWT_SECRET
        value: geneInsightSecretKeyForJWTTokenGeneration2024VeryLongAndSecure
    healthCheckPath: /actuator/health

  # Frontend Service
  - type: web
    name: geneinsight-frontend
    env: docker
    dockerfilePath: ./frontend.Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: geneinsight-backend
          property: hostWithProtocol
