services:
  # Complete GeneInsight Platform with LangChain
  - type: web
    name: geneinsight-platform
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd ml_service &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      pip install transformers torch langchain-community --no-cache-dir
    startCommand: cd ml_service && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/src/transformers_cache
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: model-cache
      mountPath: /opt/render/project/src/transformers_cache
      sizeGB: 1

databases:
  - name: geneinsight-db
    databaseName: geneinsight
    user: geneinsight_user
    plan: free
