services:
  - type: web
    name: geneinsight-langserve
    env: python
    plan: free
    buildCommand: pip install -r requirements_minimal.txt
    startCommand: python railway_minimal.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000
