spring:
  application:
    name: geneinsight
  
  datasource:
    url: jdbc:mysql://mysql:3306/geneinsight
    username: geneinsight_user
    password: geneinsight_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
  
  security:
    jwt:
      secret: geneInsightSecretKeyForJWTTokenGeneration2024
      expiration: 86400000 # 24 hours

  # Email Configuration (for development - logs OTP instead of sending)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:noreply@geneinsight.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8080

# ML Service Configuration
ml:
  service:
    url: http://ml-service:5000
    timeout: 30000

# Application Configuration
app:
  name: GeneInsight Platform

# OTP Configuration
otp:
  expiry:
    minutes: 10
  max:
    attempts: 3
    requests:
      per:
        hour: 5

# File Upload Configuration
file:
  upload:
    dir: ./uploads
    max-size: 52428800 # 50MB

# Logging Configuration
logging:
  level:
    com.geneinsight: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/geneinsight.log
