spring:
  application:
    name: geneinsight
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/geneinsight}
    username: ${SPRING_DATASOURCE_USERNAME:geneinsight_user}
    password: ${SPRING_DATASOURCE_PASSWORD:geneinsight_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
  
  security:
    jwt:
      secret: ${JWT_SECRET:geneInsightSecretKeyForJWTTokenGeneration2024}
      expiration: 86400000 # 24 hours

  # Email Configuration for Production
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:noreply@geneinsight.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

# ML Service Configuration
ml:
  service:
    url: ${ML_SERVICE_URL:http://ml-service:5000}
    timeout: 30000

# Application Configuration
app:
  name: GeneInsight Platform
  version: 1.0.0
  environment: production

# OTP Configuration
otp:
  expiry:
    minutes: ${OTP_EXPIRY_MINUTES:10}
  max:
    attempts: ${OTP_MAX_ATTEMPTS:3}
    requests:
      per:
        hour: ${OTP_MAX_REQUESTS_PER_HOUR:5}

# File Upload Configuration
file:
  upload:
    dir: ${UPLOAD_DIR:./uploads}
    max-size: ${MAX_FILE_SIZE:52428800} # 50MB

# Logging Configuration
logging:
  level:
    com.geneinsight: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/geneinsight-production.log
    max-size: 10MB
    max-history: 30

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: ${ENABLE_METRICS:true}
