spring:
  application:
    name: geneinsight
  
  datasource:
    url: jdbc:h2:mem:geneinsight;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
  
  security:
    jwt:
      secret: geneInsightSecretKeyForJWTTokenGeneration2024
      expiration: 86400000 # 24 hours

server:
  port: 8080

# ML Service Configuration
ml:
  service:
    url: http://localhost:5000
    timeout: 30000

# File Upload Configuration
file:
  upload:
    dir: ./uploads
    max-size: 52428800 # 50MB

# Logging Configuration
logging:
  level:
    com.geneinsight: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/geneinsight.log
